---
- name: Deploy Observability stack prometheus and Grafana 
  hosts: prod                     # FIX 1: Changed 'host' to 'hosts'
  become: true

  vars:
    obs_dir: /opt/statusboard/observability

  tasks:
    - name: "Ensure the observability directory exist"
      file:
        path: "{{ obs_dir }}"
        state: directory
        mode: "0755"

    - name: "Copy Observability compose yaml to VPS"
      copy:                       # FIX 2: Ansible modules must be lowercase 'copy'
        src: ../observability/compose.yaml
        dest: "{{ obs_dir }}/compose.yaml"  # FIX 3: Placed the whole path inside the quotes
        mode: "0644"

    - name: "Copy Prometheus yml to VPS"
      copy:                       
        src: ../observability/prometheus.yml
        dest: "{{ obs_dir }}/prometheus.yml"
        mode: "0644"

    - name: "Copy blackbox yml to obs_dir"
      copy:                       
        src: ../observability/blackbox.yml
        dest: "{{ obs_dir }}/blackbox.yml"
        mode: "0644"

    - name: "Start observability containers"
      shell: |
        set -e
        docker compose -f compose.yaml up -d
      args:
        chdir: "{{ obs_dir }}"    # FIX 4: Fixed indentation to align with 'chdir'

    - name: "Show running containers"
      shell: docker ps
      register: docker_ps_output
      changed_when: false
    
    - name: "Print docker output"
      debug:
        msg: "{{ docker_ps_output.stdout_lines }}"